config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: test
      host: test-endpoint-3coulnzwvyobqlekdex6.595186449594.us-east-1.redshift-serverless.amazonaws.com
      pass: JpfhOpMxvDukA4o1SHO0S5Wf
      port: 5439
      schema: public
      threads: 4
      type: redshift
      user: admin
  target: prod
